// examples/react/src/App.jsx
import { useState, useEffect, useRef, useCallback } from 'react'
import until from 'untiljs'
import './App.css'

// ============================================
// Custom Hook: useUntil - React-friendly hook for untiljs
// ============================================
function useUntil(initialValue) {
	const ref = useRef(initialValue)
	const [value, setValue] = useState(initialValue)

	// Create a RefLike object that untiljs can watch
	const refLike = useRef({
		get value() {
			return ref.current
		},
		set value(newValue) {
			ref.current = newValue
			setValue(newValue)
		}
	})

	// Sync ref with state changes
	const setValueAndRef = useCallback(newValue => {
		ref.current = newValue
		setValue(newValue)
	}, [])

	return {
		value,
		setValue: setValueAndRef,
		ref: refLike.current,
		// For direct until usage
		until: () => until(refLike.current)
	}
}

// ============================================
// Simple reactive container using useRef
// ============================================
function createReactiveRef(initialValue) {
	return {
		_value: initialValue,
		get value() {
			return this._value
		},
		set value(newValue) {
			this._value = newValue
		}
	}
}

// ============================================
// Example Card Component
// ============================================
function ExampleCard({ title, children, onClick, buttonText = 'Test' }) {
	return (
		<div className="example-card">
			<h3>{title}</h3>
			{children}
			<button onClick={onClick}>{buttonText}</button>
		</div>
	)
}

// ============================================
// Basic Usage Examples
// ============================================
function BasicExamples() {
	// toBe - using useUntil hook
	const toBe = useUntil(0)
	const [toBeResult, setToBeResult] = useState('waiting...')
	const testToBe = async () => {
		setToBeResult('waiting...')
		toBe.setValue(0)
		setTimeout(() => toBe.setValue(5), 1000)
		await toBe.until().toBe(5)
		setToBeResult(`Success! Value is now ${toBe.value}`)
	}

	// toMatch
	const toMatch = useUntil(0)
	const [toMatchResult, setToMatchResult] = useState('waiting...')
	const testToMatch = async () => {
		setToMatchResult('waiting...')
		toMatch.setValue(0)
		setTimeout(() => toMatch.setValue(10), 1000)
		await toMatch.until().toMatch(v => v > 5)
		setToMatchResult(`Success! Value ${toMatch.value} is greater than 5`)
	}

	// toBeTruthy
	const truthy = useUntil(null)
	const [truthyResult, setTruthyResult] = useState('waiting...')
	const testTruthy = async () => {
		setTruthyResult('waiting...')
		truthy.setValue(null)
		setTimeout(() => truthy.setValue({ name: 'John', age: 30 }), 1000)
		await truthy.until().toBeTruthy()
		setTruthyResult(`Success! Got object: ${JSON.stringify(truthy.value)}`)
	}

	// toBeNull
	const nullVal = useUntil('not null')
	const [nullResult, setNullResult] = useState('waiting...')
	const testBeNull = async () => {
		setNullResult('waiting...')
		nullVal.setValue('not null')
		setTimeout(() => nullVal.setValue(null), 1000)
		await nullVal.until().toBeNull()
		setNullResult('Success! Value is now null')
	}

	// toBeUndefined
	const undefinedVal = useUntil('defined')
	const [undefinedResult, setUndefinedResult] = useState('waiting...')
	const testBeUndefined = async () => {
		setUndefinedResult('waiting...')
		undefinedVal.setValue('defined')
		setTimeout(() => undefinedVal.setValue(undefined), 1000)
		await undefinedVal.until().toBeUndefined()
		setUndefinedResult('Success! Value is now undefined')
	}

	// toBeNaN
	const nanVal = useUntil(0)
	const [nanResult, setNaNResult] = useState('waiting...')
	const testBeNaN = async () => {
		setNaNResult('waiting...')
		nanVal.setValue(0)
		setTimeout(() => nanVal.setValue(NaN), 1000)
		await nanVal.until().toBeNaN()
		setNaNResult('Success! Value is now NaN')
	}

	return (
		<section className="examples-section">
			<h2>Basic Usage</h2>
			<div className="examples-grid">
				<ExampleCard title="toBe" onClick={testToBe}>
					<p>Value: {toBe.value}</p>
					<p>Result: {toBeResult}</p>
				</ExampleCard>

				<ExampleCard title="toMatch" onClick={testToMatch}>
					<p>Value: {toMatch.value}</p>
					<p>Result: {toMatchResult}</p>
				</ExampleCard>

				<ExampleCard title="toBeTruthy" onClick={testTruthy}>
					<p>Value: {JSON.stringify(truthy.value)}</p>
					<p>Result: {truthyResult}</p>
				</ExampleCard>

				<ExampleCard title="toBeNull" onClick={testBeNull}>
					<p>Value: {JSON.stringify(nullVal.value)}</p>
					<p>Result: {nullResult}</p>
				</ExampleCard>

				<ExampleCard title="toBeUndefined" onClick={testBeUndefined}>
					<p>Value: {JSON.stringify(undefinedVal.value)}</p>
					<p>Result: {undefinedResult}</p>
				</ExampleCard>

				<ExampleCard title="toBeNaN" onClick={testBeNaN}>
					<p>Value: {Number.isNaN(nanVal.value) ? 'NaN' : nanVal.value}</p>
					<p>Result: {nanResult}</p>
				</ExampleCard>
			</div>
		</section>
	)
}

// ============================================
// Change Detection Examples
// ============================================
function ChangeDetectionExamples() {
	// changed
	const changed = useUntil('initial')
	const [changedResult, setChangedResult] = useState('waiting...')
	const testChanged = async () => {
		setChangedResult('waiting...')
		changed.setValue('initial')
		setTimeout(() => changed.setValue('changed!'), 1000)
		await changed.until().changed()
		setChangedResult(`Success! Value changed to "${changed.value}"`)
	}

	// changedTimes
	const changedTimes = useUntil(0)
	const [changedTimesCount, setChangedTimesCount] = useState(0)
	const [changedTimesResult, setChangedTimesResult] = useState('waiting...')
	const testChangedTimes = async () => {
		setChangedTimesResult('waiting...')
		changedTimes.setValue(0)
		setChangedTimesCount(0)

		let count = 0
		const interval = setInterval(() => {
			count++
			changedTimes.setValue(count)
			setChangedTimesCount(count)
		}, 200)

		await changedTimes.until().changedTimes(3)
		clearInterval(interval)
		setChangedTimesResult(`Success! Value changed 3 times, final value: ${changedTimes.value}`)
	}

	return (
		<section className="examples-section">
			<h2>Change Detection</h2>
			<div className="examples-grid">
				<ExampleCard title="changed" onClick={testChanged}>
					<p>Value: "{changed.value}"</p>
					<p>Result: {changedResult}</p>
				</ExampleCard>

				<ExampleCard title="changedTimes(3)" onClick={testChangedTimes}>
					<p>Value: {changedTimes.value}</p>
					<p>Changes: {changedTimesCount}</p>
					<p>Result: {changedTimesResult}</p>
				</ExampleCard>
			</div>
		</section>
	)
}

// ============================================
// Not Modifier Examples
// ============================================
function NotModifierExamples() {
	// not.toBe
	const notToBe = useUntil(5)
	const [notToBeResult, setNotToBeResult] = useState('waiting...')
	const testNotToBe = async () => {
		setNotToBeResult('waiting...')
		notToBe.setValue(5)
		setTimeout(() => notToBe.setValue(10), 1000)
		await notToBe.until().not.toBe(5)
		setNotToBeResult(`Success! Value is no longer 5, it's ${notToBe.value}`)
	}

	// not.toBeNull
	const notNull = useUntil(null)
	const [notNullResult, setNotNullResult] = useState('waiting...')
	const testNotNull = async () => {
		setNotNullResult('waiting...')
		notNull.setValue(null)
		setTimeout(() => notNull.setValue('has value'), 1000)
		await notNull.until().not.toBeNull()
		setNotNullResult(`Success! Value is no longer null: "${notNull.value}"`)
	}

	return (
		<section className="examples-section">
			<h2>Not Modifier</h2>
			<div className="examples-grid">
				<ExampleCard title="not.toBe" onClick={testNotToBe}>
					<p>Value: {notToBe.value}</p>
					<p>Result: {notToBeResult}</p>
				</ExampleCard>

				<ExampleCard title="not.toBeNull" onClick={testNotNull}>
					<p>Value: "{notNull.value}"</p>
					<p>Result: {notNullResult}</p>
				</ExampleCard>
			</div>
		</section>
	)
}

// ============================================
// Timeout Examples
// ============================================
function TimeoutExamples() {
	// Timeout with throwOnTimeout
	const timeout = useUntil(0)
	const [timeoutResult, setTimeoutResult] = useState('waiting...')
	const testTimeout = async () => {
		setTimeoutResult('waiting...')
		timeout.setValue(0)

		try {
			await timeout.until().toBe(5, { timeout: 500, throwOnTimeout: true })
			setTimeoutResult('Unexpected success')
		} catch (error) {
			setTimeoutResult(`Timeout occurred as expected! Error: ${error.message || error}`)
		}
	}

	// Timeout without throwOnTimeout
	const timeoutNoThrow = useUntil(0)
	const [timeoutNoThrowResult, setTimeoutNoThrowResult] = useState('waiting...')
	const testTimeoutNoThrow = async () => {
		setTimeoutNoThrowResult('waiting...')
		timeoutNoThrow.setValue(0)

		const result = await timeoutNoThrow.until().toBe(5, { timeout: 500 })
		setTimeoutNoThrowResult(`Timeout without throw - returned current value: ${result}`)
	}

	return (
		<section className="examples-section">
			<h2>Timeout Options</h2>
			<div className="examples-grid">
				<ExampleCard
					title="Timeout with throwOnTimeout"
					onClick={testTimeout}
					buttonText="Test Timeout (throws)"
				>
					<p>Value: {timeout.value}</p>
					<p>Result: {timeoutResult}</p>
				</ExampleCard>

				<ExampleCard
					title="Timeout without throwOnTimeout"
					onClick={testTimeoutNoThrow}
					buttonText="Test Timeout (no throw)"
				>
					<p>Value: {timeoutNoThrow.value}</p>
					<p>Result: {timeoutNoThrowResult}</p>
				</ExampleCard>
			</div>
		</section>
	)
}

// ============================================
// Deep Comparison Examples
// ============================================
function DeepComparisonExamples() {
	// Deep object comparison
	const deepObject = useUntil({ user: { profile: { name: 'Alice' } } })
	const [deepObjectResult, setDeepObjectResult] = useState('waiting...')
	const testDeepObject = async () => {
		setDeepObjectResult('waiting...')
		deepObject.setValue({ user: { profile: { name: 'Alice' } } })

		setTimeout(() => {
			deepObject.setValue({ user: { profile: { name: 'Bob' } } })
		}, 1000)

		await deepObject.until().toMatch(v => v.user.profile.name === 'Bob', { deep: true })
		setDeepObjectResult(`Success! Deep object changed: ${JSON.stringify(deepObject.value)}`)
	}

	// Deep array comparison
	const deepArray = useUntil([1, 2, 3])
	const [deepArrayResult, setDeepArrayResult] = useState('waiting...')
	const testDeepArray = async () => {
		setDeepArrayResult('waiting...')
		deepArray.setValue([1, 2, 3])

		setTimeout(() => {
			deepArray.setValue([1, 2, 3, 4, 5])
		}, 1000)

		await deepArray.until().toBe([1, 2, 3, 4, 5], { deep: true })
		setDeepArrayResult(
			`Success! Array now has ${deepArray.value.length} items: ${deepArray.value.join(', ')}`
		)
	}

	return (
		<section className="examples-section">
			<h2>Deep Comparison</h2>
			<div className="examples-grid">
				<ExampleCard title="Deep Object Comparison" onClick={testDeepObject}>
					<p>Object: {JSON.stringify(deepObject.value)}</p>
					<p>Result: {deepObjectResult}</p>
				</ExampleCard>

				<ExampleCard title="Deep Array Comparison" onClick={testDeepArray}>
					<p>
						Array: [{Array.isArray(deepArray.value) ? deepArray.value.join(', ') : ''}]
					</p>
					<p>Result: {deepArrayResult}</p>
				</ExampleCard>
			</div>
		</section>
	)
}

// ============================================
// Array Methods Examples
// ============================================
function ArrayMethodsExamples() {
	const arrayVal = useUntil(['apple', 'banana'])
	const [arrayResult, setArrayResult] = useState('waiting...')

	const testArrayContains = async () => {
		setArrayResult('waiting...')
		arrayVal.setValue(['apple', 'banana'])

		setTimeout(() => {
			arrayVal.setValue(['apple', 'banana', 'orange', 'grape'])
		}, 1000)

		await arrayVal.until().toContains('orange')
		setArrayResult(`Success! Array now contains 'orange': ${arrayVal.value.join(', ')}`)
	}

	return (
		<section className="examples-section">
			<h2>Array Methods</h2>
			<div className="examples-grid">
				<ExampleCard title="toContains" onClick={testArrayContains}>
					<p>Array: [{Array.isArray(arrayVal.value) ? arrayVal.value.join(', ') : ''}]</p>
					<p>Result: {arrayResult}</p>
				</ExampleCard>
			</div>
		</section>
	)
}

// ============================================
// Custom Store Examples
// ============================================
function createSubscribableStore(initialValue) {
	let value = initialValue
	const listeners = new Set()

	return {
		get value() {
			return value
		},
		set value(newValue) {
			value = newValue
			listeners.forEach(cb => cb(value))
		},
		subscribe(callback) {
			listeners.add(callback)
			callback(value)
			return () => listeners.delete(callback)
		}
	}
}

function CustomStoreExamples() {
	// Create a store that persists across renders
	const storeRef = useRef(null)
	if (!storeRef.current) {
		storeRef.current = createSubscribableStore(0)
	}
	const store = storeRef.current

	const [storeValue, setStoreValue] = useState(store.value)
	const [storeResult, setStoreResult] = useState('waiting...')

	useEffect(() => {
		return store.subscribe(value => setStoreValue(value))
	}, [store])

	const testSubscribable = async () => {
		setStoreResult('waiting...')
		store.value = 0

		setTimeout(() => {
			store.value = 42
		}, 1000)

		await until(store).toBe(42)
		setStoreResult(`Success! Subscribable value is ${store.value}`)
	}

	return (
		<section className="examples-section">
			<h2>Custom Subscribable Store</h2>
			<div className="examples-grid">
				<ExampleCard title="Subscribable" onClick={testSubscribable}>
					<p>Value: {storeValue}</p>
					<p>Result: {storeResult}</p>
				</ExampleCard>
			</div>
		</section>
	)
}

// ============================================
// Async Data Loading Example
// ============================================
function AsyncDataExample() {
	const dataRef = useRef({ value: null })
	const [data, setData] = useState(null)
	const [loading, setLoading] = useState(false)
	const [loaded, setLoaded] = useState(false)

	// Create a ref-like object for until
	const refLike = {
		get value() {
			return dataRef.current.value
		}
	}

	const simulateDataLoad = useCallback(async () => {
		setLoading(true)
		setData(null)
		dataRef.current.value = null
		setLoaded(false)

		// Simulate API call
		setTimeout(() => {
			const newData = { users: ['Alice', 'Bob', 'Charlie'], count: 3 }
			dataRef.current.value = newData
			setData(newData)
			setLoading(false)
		}, 1500)

		// Wait for data to be loaded
		await until(refLike).toBeTruthy()
		setLoaded(true)
	}, [])

	return (
		<section className="examples-section">
			<h2>Async Data Loading</h2>
			<div className="examples-grid">
				<ExampleCard
					title="Wait for Data"
					onClick={simulateDataLoad}
					buttonText="Load Data"
				>
					<p>Loading: {loading.toString()}</p>
					<p>Loaded: {loaded.toString()}</p>
					<p>Data: {data ? JSON.stringify(data) : 'null'}</p>
				</ExampleCard>
			</div>
		</section>
	)
}

// ============================================
// Race Condition Example
// ============================================
function RaceConditionExample() {
	const raceRef = useRef({ value: 0 })
	const [raceValue, setRaceValue] = useState(0)
	const [raceResult, setRaceResult] = useState('waiting...')

	// Create a ref-like object for until
	const refLike = {
		get value() {
			return raceRef.current.value
		}
	}

	const testRace = async () => {
		setRaceResult('waiting...')
		raceRef.current.value = 0
		setRaceValue(0)

		// Change value after 1 second
		setTimeout(() => {
			raceRef.current.value = 5
			setRaceValue(5)
		}, 1000)

		// First to complete wins
		const result = await Promise.race([
			until(refLike).toBe(5, { timeout: 3000 }),
			new Promise(resolve => setTimeout(() => resolve('timeout-first'), 2000))
		])

		setRaceResult(
			`Race result: ${typeof result === 'number' ? `matched value ${result}` : result}`
		)
	}

	return (
		<section className="examples-section">
			<h2>Race Condition</h2>
			<div className="examples-grid">
				<ExampleCard title="Promise.race" onClick={testRace}>
					<p>Value: {raceValue}</p>
					<p>Result: {raceResult}</p>
				</ExampleCard>
			</div>
		</section>
	)
}

// ============================================
// Main App Component
// ============================================
function App() {
	return (
		<div className="container">
			<h1>untiljs React Examples</h1>
			<p className="description">
				<strong>Framework Agnostic!</strong> In React, use <code>useUntil</code> hook or
				custom RefLike objects for proper reactivity.
			</p>

			<BasicExamples />
			<ChangeDetectionExamples />
			<NotModifierExamples />
			<TimeoutExamples />
			<DeepComparisonExamples />
			<ArrayMethodsExamples />
			<CustomStoreExamples />
			<AsyncDataExample />
			<RaceConditionExample />
		</div>
	)
}

export default App

// examples/vue3/src/App.vue
<script setup>
import { ref, computed, reactive, onMounted } from 'vue'
import until from 'untiljs'

// ============================================
// Basic Usage Examples
// ============================================

// Example 1: toBe - Pass ref directly (recommended for Vue users!)
const toBeValue = ref(0)
const toBeResult = ref('waiting...')
const testToBe = async () => {
	toBeResult.value = 'waiting...'
	toBeValue.value = 0
	setTimeout(() => {
		toBeValue.value = 5
	}, 1000)
	// You can pass ref directly - no need for () => ref.value
	await until(toBeValue).toBe(5)
	toBeResult.value = `Success! Value is now ${toBeValue.value}`
}

// Example 2: toMatch - Custom condition
const toMatchValue = ref(0)
const toMatchResult = ref('waiting...')
const testToMatch = async () => {
	toMatchResult.value = 'waiting...'
	toMatchValue.value = 0
	setTimeout(() => {
		toMatchValue.value = 10
	}, 1000)
	// Pass ref directly
	await until(toMatchValue).toMatch(v => v > 5)
	toMatchResult.value = `Success! Value ${toMatchValue.value} is greater than 5`
}

// Example 3: toBeTruthy - Wait for truthy value
const truthyValue = ref(null)
const truthyResult = ref('waiting...')
const testTruthy = async () => {
	truthyResult.value = 'waiting...'
	truthyValue.value = null
	setTimeout(() => {
		truthyValue.value = { name: 'John', age: 30 }
	}, 1000)
	await until(truthyValue).toBeTruthy()
	truthyResult.value = `Success! Got object: ${JSON.stringify(truthyValue.value)}`
}

// Example 4: toBeNull - Wait for null
const nullValue = ref('not null')
const nullResult = ref('waiting...')
const testBeNull = async () => {
	nullResult.value = 'waiting...'
	nullValue.value = 'not null'
	setTimeout(() => {
		nullValue.value = null
	}, 1000)
	await until(nullValue).toBeNull()
	nullResult.value = 'Success! Value is now null'
}

// Example 5: toBeUndefined - Wait for undefined
const undefinedValue = ref('defined')
const undefinedResult = ref('waiting...')
const testBeUndefined = async () => {
	undefinedResult.value = 'waiting...'
	undefinedValue.value = 'defined'
	setTimeout(() => {
		undefinedValue.value = undefined
	}, 1000)
	await until(undefinedValue).toBeUndefined()
	undefinedResult.value = 'Success! Value is now undefined'
}

// Example 6: toBeNaN - Wait for NaN
const nanValue = ref(0)
const nanResult = ref('waiting...')
const testBeNaN = async () => {
	nanResult.value = 'waiting...'
	nanValue.value = 0
	setTimeout(() => {
		nanValue.value = NaN
	}, 1000)
	await until(nanValue).toBeNaN()
	nanResult.value = 'Success! Value is now NaN'
}

// ============================================
// Change Detection Examples
// ============================================

// Example 7: changed - Wait for any change
const changedValue = ref('initial')
const changedResult = ref('waiting...')
const testChanged = async () => {
	changedResult.value = 'waiting...'
	changedValue.value = 'initial'
	setTimeout(() => {
		changedValue.value = 'changed!'
	}, 1000)
	await until(changedValue).changed()
	changedResult.value = `Success! Value changed to "${changedValue.value}"`
}

// Example 8: changedTimes - Wait for N changes
const changedTimesValue = ref(0)
const changedTimesCount = ref(0)
const changedTimesResult = ref('waiting...')
const testChangedTimes = async () => {
	changedTimesResult.value = 'waiting...'
	changedTimesValue.value = 0
	changedTimesCount.value = 0

	const interval = setInterval(() => {
		changedTimesValue.value++
		changedTimesCount.value = changedTimesValue.value
	}, 200)

	await until(changedTimesValue).changedTimes(3)
	clearInterval(interval)
	changedTimesResult.value = `Success! Value changed 3 times, final value: ${changedTimesValue.value}`
}

// ============================================
// Not Modifier Examples
// ============================================

// Example 9: not.toBe - Inverse matching
const notToBeValue = ref(5)
const notToBeResult = ref('waiting...')
const testNotToBe = async () => {
	notToBeResult.value = 'waiting...'
	notToBeValue.value = 5
	setTimeout(() => {
		notToBeValue.value = 10
	}, 1000)
	await until(notToBeValue).not.toBe(5)
	notToBeResult.value = `Success! Value is no longer 5, it's ${notToBeValue.value}`
}

// Example 10: not.toBeNull - Wait for non-null
const notNullValue = ref(null)
const notNullResult = ref('waiting...')
const testNotNull = async () => {
	notNullResult.value = 'waiting...'
	notNullValue.value = null
	setTimeout(() => {
		notNullValue.value = 'has value'
	}, 1000)
	await until(notNullValue).not.toBeNull()
	notNullResult.value = `Success! Value is no longer null: "${notNullValue.value}"`
}

// ============================================
// Timeout Examples
// ============================================

// Example 11: Timeout with throwOnTimeout
const timeoutValue = ref(0)
const timeoutResult = ref('waiting...')
const testTimeout = async () => {
	timeoutResult.value = 'waiting...'
	timeoutValue.value = 0

	try {
		// This will timeout because value stays 0
		await until(timeoutValue).toBe(5, { timeout: 500, throwOnTimeout: true })
		timeoutResult.value = 'Unexpected success'
	} catch (error) {
		timeoutResult.value = `Timeout occurred as expected! Error: ${error.message || error}`
	}
}

// Example 12: Timeout without throwOnTimeout (returns current value)
const timeoutNoThrowValue = ref(0)
const timeoutNoThrowResult = ref('waiting...')
const testTimeoutNoThrow = async () => {
	timeoutNoThrowResult.value = 'waiting...'
	timeoutNoThrowValue.value = 0

	const result = await until(timeoutNoThrowValue).toBe(5, { timeout: 500 })
	timeoutNoThrowResult.value = `Timeout without throw - returned current value: ${result}`
}

// ============================================
// Deep Comparison Examples
// ============================================

// Example 13: Deep object comparison
const deepObject = ref({ user: { profile: { name: 'Alice' } } })
const deepObjectResult = ref('waiting...')
const testDeepObject = async () => {
	deepObjectResult.value = 'waiting...'
	deepObject.value = { user: { profile: { name: 'Alice' } } }

	setTimeout(() => {
		deepObject.value = { user: { profile: { name: 'Bob' } } }
	}, 1000)

	await until(deepObject).toMatch(v => v.user.profile.name === 'Bob', { deep: true })
	deepObjectResult.value = `Success! Deep object changed: ${JSON.stringify(deepObject.value)}`
}

// Example 14: Deep array comparison
const deepArray = ref([1, 2, 3])
const deepArrayResult = ref('waiting...')
const testDeepArray = async () => {
	deepArrayResult.value = 'waiting...'
	deepArray.value = [1, 2, 3]

	setTimeout(() => {
		deepArray.value = [1, 2, 3, 4, 5]
	}, 1000)

	await until(deepArray).toBe([1, 2, 3, 4, 5], { deep: true })
	deepArrayResult.value = `Success! Array now has ${deepArray.value.length} items: ${deepArray.value.join(', ')}`
}

// ============================================
// Array Methods Examples
// ============================================

// Example 15: toContains - Wait for array to contain value
const arrayValue = ref(['apple', 'banana'])
const arrayResult = ref('waiting...')
const testArrayContains = async () => {
	arrayResult.value = 'waiting...'
	arrayValue.value = ['apple', 'banana']

	setTimeout(() => {
		arrayValue.value = [...arrayValue.value, 'orange', 'grape']
	}, 1000)

	await until(arrayValue).toContains('orange')
	arrayResult.value = `Success! Array now contains 'orange': ${arrayValue.value.join(', ')}`
}

// ============================================
// Computed Values Examples
// ============================================

// Example 16: Watching computed values
const computedBase = ref(5)
const computedDoubled = computed(() => computedBase.value * 2)
const computedResult = ref('waiting...')
const testComputed = async () => {
	computedResult.value = 'waiting...'
	computedBase.value = 5

	setTimeout(() => {
		computedBase.value = 10
	}, 1000)

	// Computed refs work the same way!
	await until(computedDoubled).toBe(20)
	computedResult.value = `Success! Computed doubled value is ${computedDoubled.value} (base: ${computedBase.value})`
}

// ============================================
// Reactive Object Examples
// ============================================

// Example 17: Watching reactive objects (need getter for reactive)
const reactiveObj = reactive({ status: 'loading', progress: 0 })
const reactiveResult = ref('waiting...')
const testReactive = async () => {
	reactiveResult.value = 'waiting...'
	reactiveObj.status = 'loading'
	reactiveObj.progress = 0

	setTimeout(() => {
		reactiveObj.status = 'ready'
		reactiveObj.progress = 100
	}, 1000)

	// For reactive objects, use getter function
	await until(() => reactiveObj.status).toBe('ready')
	reactiveResult.value = `Success! Status: ${reactiveObj.status}, Progress: ${reactiveObj.progress}%`
}

// ============================================
// Multiple Conditions Examples
// ============================================

// Example 18: Complex condition matching
const complexCondition = ref({ loading: true, data: null, error: null })
const complexResult = ref('waiting...')
const testComplexCondition = async () => {
	complexResult.value = 'waiting...'
	complexCondition.value = { loading: true, data: null, error: null }

	setTimeout(() => {
		complexCondition.value = { loading: false, data: { items: [1, 2, 3] }, error: null }
	}, 1000)

	await until(complexCondition).toMatch(v => !v.loading && v.data !== null && !v.error, {
		deep: true
	})
	complexResult.value = `Success! Data loaded: ${JSON.stringify(complexCondition.value.data)}`
}

// ============================================
// Subscribable Pattern Example
// ============================================

// Example 19: Custom Subscribable (simulating external reactive source)
function createCustomSubscribable(initialValue) {
	let value = initialValue
	const listeners = new Set()

	return {
		get value() {
			return value
		},
		set value(newValue) {
			value = newValue
			listeners.forEach(cb => cb(value))
		},
		subscribe(callback) {
			listeners.add(callback)
			callback(value) // Initial call
			return () => listeners.delete(callback)
		}
	}
}

const customSubscribable = createCustomSubscribable(0)
const subscribableResult = ref('waiting...')
const testSubscribable = async () => {
	subscribableResult.value = 'waiting...'
	customSubscribable.value = 0

	setTimeout(() => {
		customSubscribable.value = 42
	}, 1000)

	// Subscribable objects with .value and .subscribe() are also supported
	await until(customSubscribable).toBe(42)
	subscribableResult.value = `Success! Subscribable value is ${customSubscribable.value}`
}

// ============================================
// Race Conditions Examples
// ============================================

// Example 20: Multiple promises with race
const raceValue = ref(0)
const raceResult = ref('waiting...')
const testRace = async () => {
	raceResult.value = 'waiting...'
	raceValue.value = 0

	// First to complete wins
	const result = await Promise.race([
		until(raceValue).toBe(5, { timeout: 3000 }),
		new Promise(resolve => setTimeout(() => resolve('timeout-first'), 2000))
	])

	raceResult.value = `Race result: ${typeof result === 'number' ? `matched value ${result}` : result}`
}

// Change value after 1 second
setTimeout(() => {
	raceValue.value = 5
}, 1000)

onMounted(() => {
	console.log('untiljs Vue 3 Examples loaded!')
	console.log('You can now use: until(ref) directly - no need for () => ref.value')
})
</script>

<template>
	<div class="container">
		<h1>untiljs Vue 3 Examples</h1>
		<p class="description">
			<strong>Now supports direct ref passing!</strong> Use <code>until(ref)</code> instead of
			<code>until(() => ref.value)</code> for cleaner code.
		</p>

		<h2>Basic Usage</h2>
		<section class="examples-grid">
			<div class="example-card">
				<h3>toBe</h3>
				<p>Value: {{ toBeValue }}</p>
				<p>Result: {{ toBeResult }}</p>
				<button @click="testToBe">Test toBe</button>
			</div>

			<div class="example-card">
				<h3>toMatch</h3>
				<p>Value: {{ toMatchValue }}</p>
				<p>Result: {{ toMatchResult }}</p>
				<button @click="testToMatch">Test toMatch</button>
			</div>

			<div class="example-card">
				<h3>toBeTruthy</h3>
				<p>Value: {{ truthyValue }}</p>
				<p>Result: {{ truthyResult }}</p>
				<button @click="testTruthy">Test toBeTruthy</button>
			</div>

			<div class="example-card">
				<h3>toBeNull</h3>
				<p>Value: {{ nullValue }}</p>
				<p>Result: {{ nullResult }}</p>
				<button @click="testBeNull">Test toBeNull</button>
			</div>

			<div class="example-card">
				<h3>toBeUndefined</h3>
				<p>Value: {{ undefinedValue }}</p>
				<p>Result: {{ undefinedResult }}</p>
				<button @click="testBeUndefined">Test toBeUndefined</button>
			</div>

			<div class="example-card">
				<h3>toBeNaN</h3>
				<p>Value: {{ nanValue }}</p>
				<p>Result: {{ nanResult }}</p>
				<button @click="testBeNaN">Test toBeNaN</button>
			</div>
		</section>

		<h2>Change Detection</h2>
		<section class="examples-grid">
			<div class="example-card">
				<h3>changed</h3>
				<p>Value: "{{ changedValue }}"</p>
				<p>Result: {{ changedResult }}</p>
				<button @click="testChanged">Test changed</button>
			</div>

			<div class="example-card">
				<h3>changedTimes(3)</h3>
				<p>Value: {{ changedTimesValue }}</p>
				<p>Changes: {{ changedTimesCount }}</p>
				<p>Result: {{ changedTimesResult }}</p>
				<button @click="testChangedTimes">Test changedTimes</button>
			</div>
		</section>

		<h2>Not Modifier</h2>
		<section class="examples-grid">
			<div class="example-card">
				<h3>not.toBe</h3>
				<p>Value: {{ notToBeValue }}</p>
				<p>Result: {{ notToBeResult }}</p>
				<button @click="testNotToBe">Test not.toBe</button>
			</div>

			<div class="example-card">
				<h3>not.toBeNull</h3>
				<p>Value: "{{ notNullValue }}"</p>
				<p>Result: {{ notNullResult }}</p>
				<button @click="testNotNull">Test not.toBeNull</button>
			</div>
		</section>

		<h2>Timeout Options</h2>
		<section class="examples-grid">
			<div class="example-card">
				<h3>Timeout with throwOnTimeout</h3>
				<p>Value: {{ timeoutValue }}</p>
				<p>Result: {{ timeoutResult }}</p>
				<button @click="testTimeout">Test Timeout (throws)</button>
			</div>

			<div class="example-card">
				<h3>Timeout without throwOnTimeout</h3>
				<p>Value: {{ timeoutNoThrowValue }}</p>
				<p>Result: {{ timeoutNoThrowResult }}</p>
				<button @click="testTimeoutNoThrow">Test Timeout (no throw)</button>
			</div>
		</section>

		<h2>Deep Comparison</h2>
		<section class="examples-grid">
			<div class="example-card">
				<h3>Deep Object Comparison</h3>
				<p>Object: {{ JSON.stringify(deepObject) }}</p>
				<p>Result: {{ deepObjectResult }}</p>
				<button @click="testDeepObject">Test Deep Object</button>
			</div>

			<div class="example-card">
				<h3>Deep Array Comparison</h3>
				<p>Array: {{ deepArray }}</p>
				<p>Result: {{ deepArrayResult }}</p>
				<button @click="testDeepArray">Test Deep Array</button>
			</div>
		</section>

		<h2>Array Methods</h2>
		<section class="examples-grid">
			<div class="example-card">
				<h3>toContains</h3>
				<p>Array: {{ arrayValue }}</p>
				<p>Result: {{ arrayResult }}</p>
				<button @click="testArrayContains">Test toContains</button>
			</div>
		</section>

		<h2>Computed & Reactive</h2>
		<section class="examples-grid">
			<div class="example-card">
				<h3>Computed Values</h3>
				<p>Base: {{ computedBase }}, Doubled: {{ computedDoubled }}</p>
				<p>Result: {{ computedResult }}</p>
				<button @click="testComputed">Test Computed</button>
			</div>

			<div class="example-card">
				<h3>Reactive Objects</h3>
				<p>Status: {{ reactiveObj.status }}, Progress: {{ reactiveObj.progress }}%</p>
				<p>Result: {{ reactiveResult }}</p>
				<button @click="testReactive">Test Reactive</button>
			</div>
		</section>

		<h2>Advanced Patterns</h2>
		<section class="examples-grid">
			<div class="example-card">
				<h3>Complex Condition</h3>
				<p>Loading: {{ complexCondition.loading }}</p>
				<p>Has Data: {{ !!complexCondition.data }}</p>
				<p>Error: {{ complexCondition.error }}</p>
				<p>Result: {{ complexResult }}</p>
				<button @click="testComplexCondition">Test Complex</button>
			</div>

			<div class="example-card">
				<h3>Custom Subscribable</h3>
				<p>Value: {{ customSubscribable.value }}</p>
				<p>Result: {{ subscribableResult }}</p>
				<button @click="testSubscribable">Test Subscribable</button>
			</div>

			<div class="example-card">
				<h3>Promise.race</h3>
				<p>Value: {{ raceValue }}</p>
				<p>Result: {{ raceResult }}</p>
				<button @click="testRace">Test Race</button>
			</div>
		</section>
	</div>
</template>

<style scoped>
.container {
	max-width: 1200px;
	margin: 0 auto;
	padding: 20px;
	font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
}

h1 {
	color: #42b883;
	border-bottom: 2px solid #42b883;
	padding-bottom: 10px;
}

h2 {
	color: #35495e;
	margin-top: 30px;
	border-bottom: 1px solid #ddd;
	padding-bottom: 5px;
}

.description {
	background: #f8f9fa;
	padding: 15px;
	border-radius: 8px;
	margin-bottom: 20px;
}

.description code {
	background: #e9ecef;
	padding: 2px 6px;
	border-radius: 4px;
	font-size: 14px;
}

.examples-grid {
	display: grid;
	grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
	gap: 20px;
	margin-bottom: 30px;
}

.example-card {
	border: 1px solid #e1e4e8;
	border-radius: 8px;
	padding: 15px;
	background: #fff;
	box-shadow: 0 2px 4px rgba(0, 0, 0, 0.05);
}

.example-card h3 {
	margin: 0 0 10px 0;
	color: #42b883;
	font-size: 16px;
}

.example-card p {
	margin: 5px 0;
	font-size: 14px;
	color: #666;
}

.example-card button {
	margin-top: 10px;
	padding: 8px 16px;
	background: #42b883;
	color: white;
	border: none;
	border-radius: 4px;
	cursor: pointer;
	font-size: 14px;
	transition: background 0.2s;
}

.example-card button:hover {
	background: #369970;
}
</style>
